services:
  my-website:
    image: nginx:latest
    container_name: Kees-Rezelman-Advies
    ports:
      - "8080:80" 
    volumes:
      # This maps your GitHub repo directly into the web server's public folder
      - ./:/usr/share/nginx/html:ro
    restart: always
